# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fe2b25d30138197158ac3bd7294f3a737e5120c8ea34211b27ff57c0352a84b8f9b76ca1568ed83590022b8a9ca266af2015c7a2d8643b6e7f7768db3afd70dc

test:
  secret_key_base: 9c594b16924824fb1b48ba4a8550a8bd5a730a992a71fc472906be4441bf1f51296f89b7a3a08ae7c7bc43b7d950000d96a58527da7d3e83fc8eb0a01e637805

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
